import fs from 'fs';
import path from 'path';
import { createClient } from '@supabase/supabase-js';

// Helper to load env variables from .env.local or .env.development
const loadEnv = () => {
  const envMap = {};
  const envPaths = [path.resolve('.env.local'), path.resolve('.env.development')];
  for (const envPath of envPaths) {
    if (fs.existsSync(envPath)) {
      const content = fs.readFileSync(envPath, 'utf-8');
      content.split('\n').forEach(line => {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith('#')) {
          const index = trimmed.indexOf('=');
          if (index !== -1) {
            const key = trimmed.substring(0, index).trim();
            const val = trimmed.substring(index + 1).trim();
            envMap[key] = val;
          }
        }
      });
      break;
    }
  }
  return envMap;
};

const env = loadEnv();
const supabaseUrl = env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error("❌ Supabase URL or Anon Key not found in env files.");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Preconfigured default recipient
const phone = "9779866115243"; 
// The CallMeBot API key can be set in .env.local as CALLMEBOT_API_KEY
const apiKey = env.CALLMEBOT_API_KEY || "";

const formatToNepalTime = (dateInput) => {
  if (!dateInput) return "";
  const d = new Date(dateInput);
  if (isNaN(d.getTime())) return "";
  
  // Shift by 5 hours and 45 minutes to get local Nepal time
  const nepalTimeMs = d.getTime() + (5 * 60 + 45) * 60 * 1000;
  const nepalDate = new Date(nepalTimeMs);
  
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  const year = nepalDate.getUTCFullYear();
  const month = months[nepalDate.getUTCMonth()];
  const day = nepalDate.getUTCDate();
  let hour = nepalDate.getUTCHours();
  const minute = String(nepalDate.getUTCMinutes()).padStart(2, "0");
  const ampm = hour >= 12 ? "PM" : "AM";
  hour = hour % 12;
  hour = hour ? hour : 12;
  
  return `${month} ${day}, ${year} ${hour}:${minute} ${ampm}`;
};

// Cache file to store dispatched reminder keys
const cachePath = path.resolve('scripts/sent_worker_reminders.json');

const getSentReminders = () => {
  if (fs.existsSync(cachePath)) {
    try {
      return JSON.parse(fs.readFileSync(cachePath, 'utf-8'));
    } catch (e) {
      return [];
    }
  }
  return [];
};

const saveSentReminders = (keys) => {
  const dir = path.dirname(cachePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(cachePath, JSON.stringify(keys, null, 2), 'utf-8');
};

const checkAndTriggerReminders = async () => {
  try {
    const { data: clinics, error } = await supabase
      .from('clinics')
      .select('*')
      .not('reminder_time', 'is', null);

    if (error) {
      console.error("❌ Error fetching clinics from Supabase:", error.message);
      return;
    }

    if (!clinics || clinics.length === 0) return;

    const now = Date.now();
    let sentKeys = getSentReminders();
    let hasUpdates = false;

    for (const clinic of clinics) {
      const remTime = new Date(clinic.reminder_time).getTime();
      // Check if reminder is due (within last 24 hours to prevent historic spam)
      const isDue = remTime <= now && now - remTime < 24 * 60 * 60 * 1000;
      const key = `${clinic.id}_${clinic.reminder_time}`;

      if (isDue && !sentKeys.includes(key)) {
        console.log(`⏰ Reminder reached for: ${clinic.name}`);
        
        // Fetch API key dynamically from env or configuration
        const activeApiKey = apiKey || env.CALLMEBOT_API_KEY;
        
        if (activeApiKey) {
          const timeStr = formatToNepalTime(clinic.reminder_time);
          const message = `⏰ *Mantra CRM - Callback Reminder* ⏰\n\n🏢 *Clinic:* ${clinic.name}\n👤 *Contact:* ${clinic.contact_person || "Not specified"}\n📞 *Phone:* ${clinic.phone || "Not specified"}\n📅 *Scheduled Time:* ${timeStr} (Nepal Time)\n📝 *Remarks/Notes:* ${clinic.notes || "No notes recorded"}\n\n_Generated by Server background worker._`;
          
          const cleanPhone = phone.startsWith("+") ? phone : `+${phone}`;
          const url = `https://api.callmebot.com/whatsapp.php?phone=${encodeURIComponent(cleanPhone)}&text=${encodeURIComponent(message)}&apikey=${encodeURIComponent(activeApiKey)}`;
          
          try {
            await fetch(url, { method: 'GET' });
            console.log(`✅ WhatsApp sent automatically to ${phone}`);
          } catch (err) {
            console.error(`❌ Failed to send WhatsApp to CallMeBot:`, err.message);
          }
        } else {
          console.warn("⚠️ CallMeBot API key is not configured. Set CALLMEBOT_API_KEY in .env.local to automate.");
        }

        sentKeys.push(key);
        hasUpdates = true;
      }
    }

    if (hasUpdates) {
      saveSentReminders(sentKeys);
    }
  } catch (err) {
    console.error("❌ Error in background checker loop:", err);
  }
};

console.log("🚀 Mantra CRM Server Background Worker is running...");
console.log(`📱 Preconfigured recipient number: +${phone}`);
if (apiKey) {
  console.log("🔑 CallMeBot API key loaded successfully.");
} else {
  console.warn("⚠️ No CallMeBot API key loaded yet in .env.local.");
}

setInterval(checkAndTriggerReminders, 15000);
// Initial run
checkAndTriggerReminders();
